name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for pushing tags
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to NPM
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Update npm
        run: npm install -g npm@latest # Ensure npm 11.5.1 or later is installed for OIDC support
      - run: npm ci
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: |
          git tag "v$(jq -r .version package.json)"
          git push origin "v$(jq -r .version package.json)"
      - run: npm publish
